name: project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen:
  smooth_page_indicator:
  firebase_storage: 11.6.0
  video_player: ^2.6.1
  # The followingads the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.10
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the analysis_options.yaml file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/10.jpg
    - images/20.jpeg
    - images/action.jpeg
    - images/actionback.jpeg
    - images/ad (1).jpeg
    - images/ad (2).jpeg
    - images/ad (3).jpeg
    - images/ad (4).jpeg
    - images/ad (5).jpeg
    - images/ad (6).jpeg
    - images/ad (7).jpeg
    - images/ad (8).jpeg
    - images/ad (9).jpeg
    - images/ad (10).jpeg
    - images/ad (11).jpeg
    - images/ad (12).jpeg
    - images/ad (13).jpeg
    - images/ad (14).jpeg
    - images/adventure.png
    - images/background.jpeg
    - images/comedy.png
    - images/comedy1.jpeg
    - images/comedy2.jpeg
    - images/comedy3.jpeg
    - images/comedy4.jpeg
    - images/comedy5.jpeg
    - images/comedy6.jpeg
    - images/comedy7.jpeg
    - images/comedy8.jpeg
    - images/comedy9.jpeg
    - images/comedy10.jpeg
    - images/comedy11.jpeg
    - images/comedy12.jpeg
    - images/comedy13.jpeg
    - images/comedy14.jpeg
    - images/comedy15.jpeg
    - images/cp1.jpeg
    - images/cp2.jpg
    - images/cp3.jpg
    - images/dra (1).jpeg
    - images/dra (2).jpeg
    - images/dra (3).jpeg
    - images/dra (4).jpeg
    - images/dra (5).jpeg
    - images/dra (6).jpeg
    - images/dra (7).jpeg
    - images/dra (8).jpeg
    - images/dra (9).jpeg
    - images/dra (10).jpeg
    - images/dra (11).jpeg
    - images/dra (12).jpeg
    - images/dra (13).jpeg
    - images/dra (14).jpeg
    - images/drama.png
    - images/harsh.jpg
    - images/movie_poster_1.jpeg
    - images/movie_poster_2.jpeg
    - images/movie_poster_3.jpeg
    - images/movie_poster_4.jpeg
    - images/movie_poster_5.jpeg
    - images/movie_poster_6.jpeg
    - images/movie_poster_7.jpeg
    - images/movie_poster_8.jpeg
    - images/movie_poster_9.jpeg
    - images/mw-1.jpeg
    - images/mw-2.jpeg
    - images/mw-3.jpeg
    - images/mw-4.jpeg
    - images/mw-5.jpeg
    - images/mw-6.jpeg
    - images/mw-7.jpeg
    - images/mw-8.jpeg
    - images/mw-9.jpeg
    - images/profile.jpeg
    - images/rom (1).jpeg
    - images/rom (2).jpeg
    - images/rom (3).jpeg
    - images/rom (4).jpeg
    - images/rom (5).jpeg
    - images/rom (6).jpeg
    - images/rom (7).jpeg
    - images/rom (8).jpeg
    - images/rom (9).jpeg
    - images/rom (10).jpeg
    - images/rom (11).jpeg
    - images/rom (12).jpeg
    - images/rom (13).jpeg
    - images/rom (14).jpeg
    - images/rom (15).jpeg
    - images/romance.png
    - images/up1.jpg
    - images/up2.jpg
    - images/up3.jpg
    - images/up4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages